### ISSUE TITLE
What does pressing `F` in the editor do?

### ISSUE THREAD

**Issue by ericw31415** [iblobtouch/iblobtouch.github.io#36]
Not really an issue, but I noticed this:

```
if (e.keyCode === 70) {
    input.f = false;
}
```

in `keyUphandler(e)` in gameController.js. What does this do?

**Comment by Leviterminator** [comment]
It deletes a barrel.

**Comment by Acarii** [comment]
Leviterminator is right.

In the future, if you have a question about the code, just comment on the file. Don't need to open an issue for these sort of things.

**Comment by ericw31415** [comment]
Right forgot about the `F` thing. Also, how would I comment on the file?

**Comment by Acarii** [comment]
So I've been commenting on pull requests all this time and assumed that was possible everywhere. Turns out it either isn't, or hidden really well. I'll have to get back to you if I find a way, but I guess keep using issues for this. I don't like it, but github is really stupid about a few things for no good reason.

**Comment by ericw31415** [comment]
@Acarii Yeah, I know how to comment on a pull request, but it's hard when you don't know exactly when a line of code was added.

**Comment by Acarii** [comment]
Yeah, I realized this afterwards. So basically ignore everything I said and just keep using issues as a means of discussion. Alternately, use the subreddit and mention me or blob "/u/Acarii" "/u/iblobtouch".

Only mention one of us at a time tho, reddit is weird about mentions
